# Generated by Django 4.1.5 on 2023-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todolist_created_alter_todolist_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2023-02-01', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2023-02-01', verbose_name='Дата окончания'),
        ),
    ]
